import esbuild from "esbuild";
import process from "process";
import fs from "fs"
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const testVaultPluginDir = "test-red-vault/.obsidian/plugins/red"
const copyToTestVault = () => {
  fs.copyFileSync("main.js", `${testVaultPluginDir}/main.js`);
  fs.copyFileSync("styles.css", `${testVaultPluginDir}/styles.css`);
  fs.copyFileSync("manifest.json", `${testVaultPluginDir}/manifest.json`);
  console.log(`Copied build to ${testVaultPluginDir}`);
}

esbuild
  .build({
    banner: {
      js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@codemirror/autocomplete",
      "@codemirror/closebrackets",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/comment",
      "@codemirror/fold",
      "@codemirror/gutter",
      "@codemirror/highlight",
      "@codemirror/history",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/matchbrackets",
      "@codemirror/panel",
      "@codemirror/rangeset",
      "@codemirror/rectangular-selection",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/stream-parser",
      "@codemirror/text",
      "@codemirror/tooltip",
      "@codemirror/view",
      ...builtins,
    ],
    format: "cjs",
    watch: !prod && {
      onRebuild(error, result) { !error && copyToTestVault() },
    },
    target: "es2016",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
  })
  .then(copyToTestVault)
  .catch(() => process.exit(1));
